name: Container Image
on:
  workflow_dispatch:
  push:
    branches: ['**']
    paths:
    - 'transcribe.py'
    - 'requirements.txt'
    - 'Dockerfile'
    - '.dockerignore'
    - '.github/workflows/container-image.yaml'
    if: github.event_name != 'pull_request'
  pull_request:
    types: [opened, reopened]
    branches: [main]
    paths:
    - 'transcribe.py'
    - 'requirements.txt'
    - 'Dockerfile'
    - '.dockerignore'
    - '.github/workflows/container-image.yaml'
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    environment:
      name: image
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Collect Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        flavor: latest=false
        images: |
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        tags: |
          type=raw,value=latest,enable=${{ github.event_name == 'release' }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=branch

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and publish Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-to: type=gha,mode=min
        cache-from: type=gha
